make sure we retrieved something from participant array file

diff --git a/simple-cp-test b/simple-cp-test
--- a/simple-cp-test
+++ b/simple-cp-test
@@ -17,6 +17,10 @@ P=$1
 if [ "$P" == "ARRAY" ]; then
     P=$(/get-array-line /data_out/config/$PARTICIPANT_ARRAY_FILE)
 fi
+if [ -z "$P" ]; then
+    echo "FAILed to retrieve index $AWS_BATCH_JOB_ARRAY_INDEX from $PARTICIPANT_ARRAY_FILE."
+    exit 1
+fi
 
 mkdir -p /data_out/HCP_1200/$P
 
